### ISSUE TITLE
clone最新代码echarts-for-wx页面运行不起来，控制台里有报错

### ISSUE THREAD

**Issue by BaconZhang** [NervJS/taro-sample-weapp#4]
Taro版本: v1.0.0-beta.28

复现操作：
    1、npm install
    2、npm run dev:weapp
    3、点击echarts-for-weixin示例按钮，页面为空白，且控制有报错

控制台报错：

![image](https://user-images.githubusercontent.com/13062998/45618002-ce1acb00-baa6-11e8-8ee5-2d6f495f8311.png)

![image](https://user-images.githubusercontent.com/13062998/45618112-3bc6f700-baa7-11e8-83b7-b285d0c65778.png)

**Comment by BigBigWen** [comment]
我也遇到了同样的问题

**Comment by luckyadam** [comment]
已修复，请拉取最新代码，并且安装依赖~

**Comment by BaconZhang** [comment]
谢谢，更新依赖后问题已经解决
