### ISSUE TITLE
如果我选择使用antv-f2，那么它的使用方法同示例上的一样吗？

### ISSUE THREAD

**Issue by mdothy** [NervJS/taro-sample-weapp#6]

**Comment by mdothy** [comment]
组件需绑定 opts 变量，例：<ff-canvas id="mychart-dom-bar" canvas-id="mychart-bar" opts="{{ opts }}"></ff-canvas>
这是同echart一样的写法过程中出现的问题，不知道是不是无法识别opts这个对象

**Comment by luckyadam** [comment]
可以给下你的写法示例
