### ISSUE TITLE
无法加载wxParse.wxss文件

### ISSUE THREAD

**Issue by LYfirstday** [NervJS/taro-sample-weapp#8]
只要我使用第三方文件，所有第三方的标签全都报错   版本1.0.0-beta.26
![image](https://user-images.githubusercontent.com/25970534/46589649-b69b9480-cade-11e8-9bce-d1ae1a7b6333.png)
而且你这个demo我运行不起来
![image](https://user-images.githubusercontent.com/25970534/46589674-08441f00-cadf-11e8-8ac8-472bdb77b2fb.png)

**Comment by luckyadam** [comment]
看下 config/index.js ，当前 Taro 版本需要自行配置 copy，后续版本就不用了

**Comment by LYfirstday** [comment]
感谢回复！
问题解决了，虽然eslint在报错，并没有影响保存和提交代码.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Li,Weitao <notifications@github.com>
发送时间: Monday, October 8, 2018 5:46:36 PM
收件人: NervJS/taro-sample-weapp
抄送: LYi; Author
主题: Re: [NervJS/taro-sample-weapp] 无法加载wxParse.wxss文件 (#8)


看下 config/index.js ，当前 Taro 版本需要自行配置 copy，后续版本就不用了

―
